ALTER TABLE students ADD CHECK ( AGE >=16 );
ALTER TABLE students ALTER COLUMN name SET NOT NULL;
ALTER TABLE students ADD CONSTRAINT name_unique UNIQUE (name);
ALTER TABLE students ALTER COLUMN age SET  DEFAULT 20;